services:
  mysql:
    image: mysql:8.0
    container_name: watchshop-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: dotnet_all_in1
      MYSQL_USER: dotnet_all_in2
      MYSQL_PASSWORD: dotnet_all_in3
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: watchshop-redis
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: watchshop-admin-api
    depends_on:
      - mysql
      - redis
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "8080:8080"

volumes:
  mysql_data:
